# Generated by Django 5.0.4 on 2024-05-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_admin_parent_teacher_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='need_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
